language: python
os: linux

jobs:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: "pypy"
    - python: "pypy3"
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install scrutinizer-ocular
script:
    - PYTHONHASHSEED=0 python -m pytest --cov=vdf tests
after_success:
    - coveralls
    - ocular --data-file ".coverage"
