language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"
install:
    - make init
    - pip install coveralls
    - pip install scrutinizer-ocular
script:
    make test
after_success:
    - coveralls
    - ocular --data-file ".coverage"
