language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
    - "pypy"
    - "pypy3"
    - "pypy-5.3.1"
install:
    - make init
    - pip install coveralls==1.1
    - pip install scrutinizer-ocular
script:
    make test
after_success:
    - coveralls
    - ocular --data-file ".coverage"
